# Generated by Django 4.2.7 on 2023-12-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagementSystemModules', '0005_remove_subject_staff_remove_subject_studentclass_and_more'),
        ('Staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Staffs.staff')),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SchoolManagementSystemModules.studentclass')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SchoolManagementSystemModules.subject')),
            ],
        ),
    ]
