# Generated by Django 4.2.7 on 2023-12-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staffs', '0003_assignsubject_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubject',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Staffs.staff'),
        ),
    ]
