# Generated by Django 4.2.7 on 2023-12-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staffs', '0004_alter_assignsubject_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignsubject',
            name='staff',
        ),
    ]
