# Generated by Django 4.2.7 on 2023-12-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staffs', '0005_remove_assignsubject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignsubject',
            name='staff',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Staffs.staff'),
            preserve_default=False,
        ),
    ]
