# Generated by Django 4.2.7 on 2023-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffs', '0006_assignsubject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AssignSubject',
        ),
    ]
