# Generated by Django 4.2.7 on 2023-12-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_gender_section_subject'),
        ('Staffs', '0007_staff_active_delete_assignsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.gender'),
        ),
    ]
