# Generated by Django 4.2.7 on 2023-12-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_section_subject_remove_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_roll',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
