# Generated by Django 4.2.7 on 2023-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_remove_routine_end_date_remove_routine_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
