# Generated by Django 4.2.7 on 2023-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_alter_routine_end_time_alter_routine_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.CharField(max_length=250),
        ),
    ]
