# Generated by Django 4.2.7 on 2023-12-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staffs', '0007_staff_active_delete_assignsubject'),
        ('Students', '0017_alter_result_passorfail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='Students.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Staffs.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('1', 'Present'), ('2', 'Late'), ('1', 'Absent')], max_length=250),
        ),
    ]
