# Generated by Django 4.2.7 on 2023-12-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0020_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='classIns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Students.class'),
        ),
    ]
