# Generated by Django 4.2.7 on 2023-12-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0021_alter_notice_classins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Students.fee')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Students.student')),
            ],
        ),
    ]
