# Generated by Django 4.2.7 on 2023-12-24 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0022_fee_studentfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='date_created',
        ),
        migrations.AddField(
            model_name='studentfee',
            name='pay_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
