# Generated by Django 4.2.7 on 2023-12-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0023_remove_fee_date_created_studentfee_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
    ]
