# Generated by Django 4.2.7 on 2023-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0025_month_studentfee_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bith_indentificaion_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_guardian',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_student',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
