# Generated by Django 4.2.7 on 2023-12-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
