# Generated by Django 4.2.7 on 2023-12-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagementSystemModules', '0002_remove_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='version',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
