# Generated by Django 4.2.7 on 2023-12-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staffs', '0001_initial'),
        ('SchoolManagementSystemModules', '0003_remove_classroom_students_remove_classroom_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Staffs.staff')),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SchoolManagementSystemModules.studentclass')),
            ],
        ),
    ]
