# Generated by Django 4.2.7 on 2023-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagementSystemModules', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='studentclass',
        ),
        migrations.AddField(
            model_name='subject',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
